name: Node.js CI

on:
  push:
    branches: [ main, feature-1 ]  # Replace with your branch names
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Change to your Node.js version if needed

    - name: Install dependencies
      run: npm install

    - name: Run tests or Node.js script
      run: npm test
